My feature branch
Technology-Students-Association/TSA-Website-FrontEnd pull request #1
Opened 2024-05-29 06:31 UTC by 12492sachet

2024-05-29 14:31 UTC, Kalanza approved these changes

2024-05-29 14:32 UTC, Kalanza approved these changes
Nice work

2024-06-12 13:08 UTC, Cli4d requested changes
The website looks nice. I would suggest making the few changes I have suggested. For the Categories section overflow, just look at either using padding or height. I suggested padding but you don't have to follow that

2024-07-24 04:56 UTC, Cli4d approved these changes
Looks Good To Me ✅

2024-07-24 04:56 UTC, merged